# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: build-and-test (reusable workflow)

on:
  workflow_call:
    inputs:
      dotnet:
        description: "an array of { version: '8.0.x', framework: 'net8.0'}"
        required: true
        type: string
        #default:
        #  - version: '6.0.x'
        #    framework: 'net6.0'
        #  - version: '7.0.x'
        #    framework: 'net7.0'
        #  - version: '8.0.x'
        #    framework: 'net8.0'
        #  - version: '9.0.x'
        #    framework: 'net9.0'
      configuration:
        description: "The configuration to use for building the package. The default is 'Debug' and 'Release'."
        required: true
        type: string
        #default: [ 'Debug', 'Release' ]
                  
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet: ${{ fromJson(inputs.dotnet) }}
        configuration: ${{ inputs.configuration }}
    env:
      NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages
    steps:
      - run: echo "The configuration is ${{ inputs.configuration }}."
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls -la ${{ github.workspace }}
    
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet.version }}
          global-json-file: global.json
          cache: false
      - name: Display dotnet version
        run: dotnet --version
    
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore --configuration ${{ matrix.configuration }}

      - name: Test with the dotnet CLI
        run: dotnet test --no-build --framework ${{ matrix.dotnet.framework }} --configuration ${{ matrix.configuration }} --verbosity normal --logger trx --results-directory "TestResults-${{ matrix.configuration }}-${{ matrix.dotnet.framework }}"
      - name: Upload dotnet test results
        uses: actions/upload-artifact@v4
        with:
          name: dontet-results-${{ matrix.configuration }}-${{ matrix.dotnet.framework }}
          path: TestResults-${{ matrix.configuration }}-${{ matrix.dotnet.framework }}
        if: ${{ always() }}

      - run: echo "This job's status is ${{ job.status }}."
      