# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: build
on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths-ignore:
      - "*.md"
  pull_request:
    branches: [ master ]
    paths-ignore:
      - "*.md"
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hi, ${{ github.actor }}!"
      - run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub!"
    
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "Your repository has been cloned to the runner."
      - name: List files in the repository
        run: |
          ls -la ${{ github.workspace }}
      - run: echo "The workflow is now ready to test your code on the runner."
    
      - name: build and test
        uses: ./.github/workflows/build-n-test
        with:
          configuration: 'Release'
        secrets:
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: echo "This job's status is ${{ job.status }}."
      