# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: build
on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths-ignore:
      - "*.md"
  pull_request:
    branches: [ master ]
    paths-ignore:
      - "*.md"

jobs:
  build-and-test:
    strategy:
      matrix:
        dotnet: [ { version: '6.0.x', framework: 'net6.0'}, { version: '7.0.x', framework: 'net7.0'} ]
        configuration: [ 'Debug', 'Release' ]
    uses: myvas/AspNetCore.Email/.github/workflows/build-and-test.yml@9.0
    with:
      dotnet: ${{ matrix.dotnet }}
      configuration: ${{ matrix.configuration }}
      