# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: test

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths-ignore:
      - "*.md"
  pull_request:
    branches: [ master ]
    paths-ignore:
      - "*.md"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
    
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
    
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      - name: Display dotnet version
        run: dotnet --version
    
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Show working-directory
        run: |
          pwd
          ls

  test:
    needs: [ build ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        framework: [ 'net6.0', 'net7.0', 'net8.0', 'net9.0' ]
    steps:
    - name: Enter the build dir
      run: |
        ls ${{ github.workspace }}
        pwd
        cd ${{ github.workspace }}
    - name: Test with the dotnet CLI
      run: dotnet test --framework ${{ matrix.framework }} --no-build --verbosity normal --logger trx --results-directory "TestResults-${{ matrix.framework }}"
    - name: Upload dotnet test results
      uses: actions/upload-artifact@v4
      with:
        name: dontet-results-${{ matrix.framework }}
        path: TestResults-${{ matrix.framework }}
      if: ${{ always() }}
    - run: echo "This job's status is ${{ job.status }}."
