name: deploy

on:
  workflow_dispatch:
  release:
    types: [ published ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
    - run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub!"
    - run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
    
    - name: Check out repository code
      uses: actions/checkout@v4
    - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
    - run: echo "The workflow is now ready to test your code on the runner."
    - name: List files in the repository
      run: |
        ls -la ${{ github.workspace }}
        pwd
        cat ./.github/workflows/build-n-test/action.yml

    - name: Call reusable workflow to build and test
      uses: ./.github/workflows/build-n-test
      with:
        configuration: "Release"
    
    - name: Create the NuGet package (.nupkg)
      run: dotnet pack --configuration Release
    #- name: Publish the NuGet package to nuget.org
    #  run: dotnet nuget push "**/bin/Release/*.nupkg" -k $NUGET_AUTH_TOKEN -s https://api.nuget.org/v3/index.json --skip-duplicate
    #  env:
    #    NUGET_AUTH_TOKEN: ${{ secrets.NUGET_TOKEN }}
        # You should create this repository secret on https://github.com/myvas/AspNetCore.Email/settings/secrets/actions
    - run: echo "This job's status is ${{ job.status }}."
