# This workflow will publish NuGet packages to nuget.org
# For more information see: https://docs.github.com/en/actions/use-cases-and-examples/publishing-packages/about-packaging-with-github-actions

name: publish

on:
  workflow_dispatch:
  release:
    types: [ published ]

jobs:
  pack-and-publish:
    uses: ./.github/workflows/pack-and-publish.yml
    secrets:
      NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}
